language: node_js
node_js:
- '4'
- '6'
- '8'
notifications:
  slack:
    secure: Fdl/sQMTl86jYN1r1CRRRQRgyFoslvrhkkfnM2JSdx4gODPgyg4nCPSKtU5j9wpSbbkq9A+YBeFv+Suh+xYNviegqa0AZbztydfFzVDS7xw43B/uR9Y4LwaP5Kis1WGuIOHawwFISNO3hTUei6aybKiKKlxvfqrARJaO01+Xxrg=
env:
  global:
  - secure: j1wbqZQkUlZy3F8rRxPxdQQq7g1UeijSRfnqggKIut2v2PDd/F0fQJUoEPOO2ohc4hxu6lg5GLLO1EIovbUkdRy5NBw7o+ICRAFrlpts7iyV5fhc9YwAA8Bexb41GvvBF1vhMw9YI16HGTHRAonM+XzBsjU/COdWEYr/3sSE9Bjs/kMdO9K2/31P9lNjxS33BrWqH6+/VFtt+DuncpOk5GkXsRKElPxUq1j7g/1p63x6qm+34jH50HdbfoMvstJq+iNXDswqqAwrHiZwwpcuYmtzpoXstV3FyrdpGPCL1o/4dmxqSlK9mom8KZuUtxVjhtKcWRp5y3s+hEKFYIdw5lV1B7RLDe1GzQ2AhiMOOkIlCIGOqb+9DHFvreUi2wIj21REvz7oCpEUcNp9jsR9hxUPkfBzfPocGlpnw8q/gDfQig5jnEkoYaMPTFp0+5U44mxUmkR0xXXCmUIvvvpo8VE432tRTM8fXcKJHPUnQT0s9IL4e93q6Swu2qIxAzyoyzvOh2Uak3mSNZndcG8Q8dqUasqXHL2t6mRKyW4PnFdFTmCwciS2XBS4i6IqCJQJmXXYzqt+0R/ahiPgk4tpuBbhdm5HTEzT/5Jcxcfby2LlzFKiPS4AcfZfLuCtA8a7Evsrx9KfDtNYF33IUCkKaDsUBwHPrdSEgGbAxESEIl0=
  - secure: V450XAVLxNeAdSVy0OqkeMOQM3LZbaArUOAuJuX/NMa2ljeBwDkrZlbx2rgMKB3rAabQ1/yJUy+i3ziAYfZUhXEYNnSV9G/VlIo7LfShuSnRj9jTWWXXjJdcDfmxbXwam+f5zKLZdcmRBxs0bQHua7ke19NZqWNeA6DOqDJJJ5FvQmXVR3LBH7DqyXwpk4X6VaHBAQLbSx4cPP/J8KGwnSHqOenzIj2i+t21NaenR8m7V/pkLS/ARh5POlqOCc90UcpmC5d+o7n9MQDeZ8EszMQCYKtiAWAQx1neon0QoK39JG0MBJMr4JIOlk0oXSYxr51ihqTsaSjjKPeArBtY01Mtzk9fIqI2XGwZTEFC7g7Z8l+eNgaHANrjFgzAGKDA8EWuxJYqk9Z0+qtqYxc9FnOsu/daTHj7pPaWDpCQx1yD2XZuSP+YIObzf+Ugw/jjlocilizTrLlj1E6zyZxXPogfh0IkbVVai6MdWwliv5u7JhPZ4u/IZBcUaxy6Occ6dmaIEPM6VMBYaF3cxF29rHpbGYF+t4MllRCkjt41xzxboNRMrSFkCb02ZoT6ncU9Ouk+ki3jhZFKO70FYKI01bG1An8oqtoV5eYSGl+gNEEpU/cDGbopY/XB+z/Y0jATg+bvl5aQTuJnGvgxieFq86HKQReCIpZXxhlrXxuptw4=
after_success:
- chmod +x ./docker/scripts/run.sh
- ./docker/scripts/run.sh